#!/bin/env bash
source $HOME/.bash.d/support

prompt_line_one() {
echo -n $BLUE"["$RESET
username
prompt_for_git
echo $BLUE"]"$RESET
}

prompt_line_two() {
cwd
emblem
}

prompt_line_three() {
emblem
}

username() {
echo -n $PURPLE"\u"$RESET
}

cwd() {
echo -n $RED"\w"$CLEAR
}

## Git
prompt_for_git() {
git --version > /dev/null 2>&1;
if [ "$?" -ne "0" ]; then \
  return
else
  source $HOME/.bash.d/git
fi
if [ -d .git ]; then
  prompt_for_git_branch
  prompt_for_git_stashes
  prompt_for_git_cleanliness
fi
}

prompt_for_rvm() {
# Check for RVM
if [ -f `which rvm` ]; then \
echo  "\[\e[0;32m\]Ruby: `rvm-prompt | cut -d "@" -f 1` | Gemset: `rvm gemset name | sed s:.*/::`"; fi
echo -n "\[\e[0;31m\]\w"
}

emblem() {
echo -n "\[\e[0;36m\]"
check_for_unicode ⚡ $
echo -n " \[\e[0m\]"
}

load_functions() {
prompt_line_one
prompt_line_two
#prompt_line_three
}

PS1="$(load_functions)"
